/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace SharpOTP.Remote.Messaging
{

  [Serializable]
  public partial class Message : TBase
  {
    private Actions _Action;
    private string _Code;
    private byte[] _Payload;
    private RemotingException _Exception;
    private string _To;
    private string _ReplyTo;
    private long _CorrentionId;

    public Actions Action
    {
      get
      {
        return _Action;
      }
      set
      {
        __isset.Action = true;
        this._Action = value;
      }
    }

    public string Code
    {
      get
      {
        return _Code;
      }
      set
      {
        __isset.Code = true;
        this._Code = value;
      }
    }

    public byte[] Payload
    {
      get
      {
        return _Payload;
      }
      set
      {
        __isset.Payload = true;
        this._Payload = value;
      }
    }

    public RemotingException Exception
    {
      get
      {
        return _Exception;
      }
      set
      {
        __isset.Exception = true;
        this._Exception = value;
      }
    }

    public string To
    {
      get
      {
        return _To;
      }
      set
      {
        __isset.To = true;
        this._To = value;
      }
    }

    public string ReplyTo
    {
      get
      {
        return _ReplyTo;
      }
      set
      {
        __isset.ReplyTo = true;
        this._ReplyTo = value;
      }
    }

    public long CorrentionId
    {
      get
      {
        return _CorrentionId;
      }
      set
      {
        __isset.CorrentionId = true;
        this._CorrentionId = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool Action;
      public bool Code;
      public bool Payload;
      public bool Exception;
      public bool To;
      public bool ReplyTo;
      public bool CorrentionId;
    }

    public Message() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 2:
            if (field.Type == TType.I32) {
              Action = (Actions)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              Code = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              Payload = iprot.ReadBinary();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.Struct) {
              Exception = new RemotingException();
              Exception.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.String) {
              To = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.String) {
              ReplyTo = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == TType.I64) {
              CorrentionId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Message");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.Action) {
        field.Name = "Action";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)Action);
        oprot.WriteFieldEnd();
      }
      if (Code != null && __isset.Code) {
        field.Name = "Code";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Code);
        oprot.WriteFieldEnd();
      }
      if (Payload != null && __isset.Payload) {
        field.Name = "Payload";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(Payload);
        oprot.WriteFieldEnd();
      }
      if (Exception != null && __isset.Exception) {
        field.Name = "Exception";
        field.Type = TType.Struct;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        Exception.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (To != null && __isset.To) {
        field.Name = "To";
        field.Type = TType.String;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(To);
        oprot.WriteFieldEnd();
      }
      if (ReplyTo != null && __isset.ReplyTo) {
        field.Name = "ReplyTo";
        field.Type = TType.String;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ReplyTo);
        oprot.WriteFieldEnd();
      }
      if (__isset.CorrentionId) {
        field.Name = "CorrentionId";
        field.Type = TType.I64;
        field.ID = 8;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(CorrentionId);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Message(");
      sb.Append("Action: ");
      sb.Append(Action);
      sb.Append(",Code: ");
      sb.Append(Code);
      sb.Append(",Payload: ");
      sb.Append(Payload);
      sb.Append(",Exception: ");
      sb.Append(Exception== null ? "<null>" : Exception.ToString());
      sb.Append(",To: ");
      sb.Append(To);
      sb.Append(",ReplyTo: ");
      sb.Append(ReplyTo);
      sb.Append(",CorrentionId: ");
      sb.Append(CorrentionId);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
